<a href="https://colab.research.google.com/github/davialvesguerra/numpy/blob/master/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Import the numpy package under the name np (★☆☆)

In [1]:
import numpy as np

2. Print the numpy version and the configuration (★☆☆)

In [2]:
np.__version__

'1.18.5'

3. Create a null vector of size 10 (★☆☆)

In [3]:
np.zeros((10))

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

4. How to find the memory size of any array (★☆☆)

In [4]:
np.size(np.zeros(10))

10

5. How to get the documentation of the numpy add function from the command line?

In [5]:
np.__doc__

'\nNumPy\n=====\n\nProvides\n  1. An array object of arbitrary homogeneous items\n  2. Fast mathematical operations over arrays\n  3. Linear Algebra, Fourier Transforms, Random Number Generation\n\nHow to use the documentation\n----------------------------\nDocumentation is available in two forms: docstrings provided\nwith the code, and a loose standing reference guide, available from\n`the NumPy homepage <https://www.scipy.org>`_.\n\nWe recommend exploring the docstrings using\n`IPython <https://ipython.org>`_, an advanced Python shell with\nTAB-completion and introspection capabilities.  See below for further\ninstructions.\n\nThe docstring examples assume that `numpy` has been imported as `np`::\n\n  >>> import numpy as np\n\nCode snippets are indicated by three greater-than signs::\n\n  >>> x = 42\n  >>> x = x + 1\n\nUse the built-in ``help`` function to view a function\'s docstring::\n\n  >>> help(np.sort)\n  ... # doctest: +SKIP\n\nFor some objects, ``np.info(obj)`` may provide a

6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [6]:
x = np.zeros(10)
x[4] = 1
x

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [7]:
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

8. Reverse a vector (first element becomes last) (★☆☆)

In [8]:
x = np.arange(50)
x[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [9]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [13]:
x = np.array([1,2,0,0,4,0])
np.where(x==0)



(array([2, 3, 5]),)

11. Create a 3x3 identity matrix (★☆☆)

In [24]:
np.eye(3,3,0)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [34]:
np.random.random([3,3,3])

array([[[0.80603179, 0.25572121, 0.51522137],
        [0.33413976, 0.36779339, 0.19612504],
        [0.62917761, 0.22935972, 0.32500944]],

       [[0.3795069 , 0.45336891, 0.7528269 ],
        [0.16252611, 0.47141764, 0.06661376],
        [0.17094028, 0.09516509, 0.51005557]],

       [[0.39668124, 0.23683294, 0.80256453],
        [0.80343865, 0.85478172, 0.91265049],
        [0.98899388, 0.03517066, 0.59042383]]])

13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [52]:
x = np.random.random((10,10))
print(x.min(),"\n",x.max())


0.0014763874876103644 
 0.99025344387072


14. Create a random vector of size 30 and find the mean value (★☆☆)

In [71]:
np.random.randint(low = 0, high = 101, size = (30,2)).mean()

53.35

15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [ ]:
x = np.ones((10,10))
x[1:-1,1:-1] = 0
x

16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [104]:
x = np.ones((5,5))
x = np.pad(x, pad_width=1, mode='constant', constant_values=0)


array([2., 1., 1., 1., 1.])