<a href="https://colab.research.google.com/github/davialvesguerra/numpy/blob/master/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Import the numpy package under the name np (★☆☆)

In [1]:
import numpy as np

2. Print the numpy version and the configuration (★☆☆)

In [ ]:
np.__version__

'1.18.5'

3. Create a null vector of size 10 (★☆☆)

In [ ]:
np.zeros((10))

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

4. How to find the memory size of any array (★☆☆)

In [ ]:
np.size(np.zeros(10))

10

5. How to get the documentation of the numpy add function from the command line?

In [ ]:
np.__doc__

'\nNumPy\n=====\n\nProvides\n  1. An array object of arbitrary homogeneous items\n  2. Fast mathematical operations over arrays\n  3. Linear Algebra, Fourier Transforms, Random Number Generation\n\nHow to use the documentation\n----------------------------\nDocumentation is available in two forms: docstrings provided\nwith the code, and a loose standing reference guide, available from\n`the NumPy homepage <https://www.scipy.org>`_.\n\nWe recommend exploring the docstrings using\n`IPython <https://ipython.org>`_, an advanced Python shell with\nTAB-completion and introspection capabilities.  See below for further\ninstructions.\n\nThe docstring examples assume that `numpy` has been imported as `np`::\n\n  >>> import numpy as np\n\nCode snippets are indicated by three greater-than signs::\n\n  >>> x = 42\n  >>> x = x + 1\n\nUse the built-in ``help`` function to view a function\'s docstring::\n\n  >>> help(np.sort)\n  ... # doctest: +SKIP\n\nFor some objects, ``np.info(obj)`` may provide a

6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [ ]:
x = np.zeros(10)
x[4] = 1
x

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [ ]:
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

8. Reverse a vector (first element becomes last) (★☆☆)

In [ ]:
x = np.arange(50)
x[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [ ]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [ ]:
x = np.array([1,2,0,0,4,0])
np.where(x==0)



(array([2, 3, 5]),)

11. Create a 3x3 identity matrix (★☆☆)

In [ ]:
np.eye(3,3,0)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.random.random([3,3,3])

array([[[0.80603179, 0.25572121, 0.51522137],
        [0.33413976, 0.36779339, 0.19612504],
        [0.62917761, 0.22935972, 0.32500944]],

       [[0.3795069 , 0.45336891, 0.7528269 ],
        [0.16252611, 0.47141764, 0.06661376],
        [0.17094028, 0.09516509, 0.51005557]],

       [[0.39668124, 0.23683294, 0.80256453],
        [0.80343865, 0.85478172, 0.91265049],
        [0.98899388, 0.03517066, 0.59042383]]])

13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [ ]:
x = np.random.random((10,10))
print(x.min(),"\n",x.max())


0.0014763874876103644 
 0.99025344387072


14. Create a random vector of size 30 and find the mean value (★☆☆)

In [ ]:
np.random.randint(low = 0, high = 101, size = (30,2)).mean()

53.35

15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [ ]:
x = np.ones((10,10))
x[1:-1,1:-1] = 0
x

16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [ ]:
x = np.ones((5,5))
x = np.pad(x, pad_width=1, mode='constant', constant_values=0)


array([2., 1., 1., 1., 1.])

17. What is the result of the following expression? (★☆☆)
\
0 * np.nan \
np.nan == np.nan\
np.inf > np.nan\
np.nan - np.nan\
np.nan in set([np.nan])\
 0.3 == 3 * 0.1\

In [ ]:
0*np.nan 

nan

In [ ]:
np.nan == np.nan

False

In [ ]:
np.inf > np.nan

inf

In [ ]:
np.nan - np.nan

nan

In [ ]:
np.nan in set([np.nan])

True

In [ ]:
0.3 == 0.1*3

False

18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [ ]:
np.diag(np.arange(1,5),k=-1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [ ]:
Z = np.zeros((8,8),dtype=int)
Z[1::2,::2] = 1
Z[::2,1::2] = 1
Z

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [ ]:
np.unravel_index(99,(6,7,8))

(1, 5, 3)

21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [ ]:
x = np.array([[0,1],[1,0]])
np.tile(x,(4,4))

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

22. Normalize a 5x5 random matrix (★☆☆)

In [4]:
np.random.normal(size=(5,5))

array([[ 0.25472428, -1.12244844, -0.73110511,  0.53115328,  2.35253172],
       [-1.65952598, -0.43012427,  0.08588392,  1.32861981,  0.69172219],
       [ 0.47220307, -0.43921593, -0.43233789,  1.6062756 , -0.57382786],
       [-0.35545336,  0.97773006, -0.94786891,  0.05834642, -0.04122784],
       [ 0.65559737,  1.24700931, -0.17568479,  0.51161116, -0.22665593]])

23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [ ]:
 color = np.dtype([("r", np.ubyte, 1),
                  ("g", np.ubyte, 1),
                  ("b", np.ubyte, 1),
                  ("a", np.ubyte, 1)])
 
 color

24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [13]:
np.dot(np.random.randint(0,100,(5,3)), np.random.randint(0,100,(3,2)))

np.random.randint(0,100,(5,3))@np.random.randint(0,100,(3,2))

array([[10050, 13486],
       [ 5454,  8413],
       [14364, 16846],
       [11712, 10503],
       [ 9024,  8498]])

25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [18]:
Z = np.arange(11)
Z[(3 < Z) & (Z < 8)] *= -1
x

[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


26. What is the output of the following script? (★☆☆)


print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

In [24]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

10
10
